api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/galaxy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect