spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/galaxy
    username: postgres
    password: postgres
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update